name: homeventory
description: This app is create for demo app submissions to Awesome Appwrite! (Hacktoberfest 2022).

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  appwrite: ^8.1.0
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.5
  flutter_svg: ^1.1.5
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  flutter_gen_runner: ^5.0.1
  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/common/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
